class YahooQuote{
  
     language;
     region;
     quoteType;
     quoteSourceName;
     triggerable;
     currency;
     regularMarketChange;
     regularMarketChangePercent;
     regularMarketTime;
     regularMarketPrice;
     regularMarketDayHigh;
     regularMarketDayRange;
     regularMarketDayLow;
     regularMarketVolume;
     regularMarketPreviousClose;
     bid;
     ask;
     bidSize;
     askSize;
     fullExchangeName;
     financialCurrency;
     regularMarketOpen;
     averageDailyVolume3Month;
     averageDailyVolume10Day;
     fiftyTwoWeekLowChange;
     fiftyTwoWeekLowChangePercent;
     fiftyTwoWeekRange;
     fiftyTwoWeekHighChange;
     fiftyTwoWeekHighChangePercent;
     fiftyTwoWeekLow;
     fiftyTwoWeekHigh;
     dividendDate;
     earningsTimestamp;
     earningsTimestampStart;
     earningsTimestampEnd;
     trailingAnnualDividendRate;
     trailingPE;
     trailingAnnualDividendYield;
     epsTrailingTwelveMonths;
     epsForward;
     epsCurrentYear;
     priceEpsCurrentYear;
     sharesOutstanding;
     bookValue;
     fiftyDayAverage;
     fiftyDayAverageChange;
     fiftyDayAverageChangePercent;
     twoHundredDayAverage;
     twoHundredDayAverageChange;
     twoHundredDayAverageChangePercent;
     marketCap;
     forwardPE;
     priceToBook;
     sourceInterval;
     exchangeDataDelayedBy;
     marketState;
     gmtOffSetMilliseconds;
     esgPopulated;
     exchange;
     shortName;
     longName;
     messageBoardId;
     exchangeTimezoneName;
     market;
     tradeable;
     exchangeTimezoneShortName;
     firstTradeDateMilliseconds;
     priceHint;
     displayName;
     symbol;

    YahooQuote(){
      
    }
}