class YahooQuote{

  
    String language;
    String region;
    String quoteType;
    String quoteSourceName;
    bool triggerable;
    String currency;
    num regularMarketChange;
    num regularMarketChangePercent;
    num regularMarketTime;
    num regularMarketPrice;
    num regularMarketDayHigh;
    String regularMarketDayRange;
    num regularMarketDayLow;
    num regularMarketVolume;
    num regularMarketPreviousClose;
    num bid;
    num ask;
    num bidSize;
    num askSize;
    String fullExchangeName;
    String financialCurrency;
    num regularMarketOpen;
    num averageDailyVolume3Month;
    num averageDailyVolume10Day;
    num fiftyTwoWeekLowChange;
    num fiftyTwoWeekLowChangePercent;
    String fiftyTwoWeekRange;
    num fiftyTwoWeekHighChange;
    num fiftyTwoWeekHighChangePercent;
    num fiftyTwoWeekLow;
    num fiftyTwoWeekHigh;
    num dividendDate;
    num earningsTimestamp;
    num earningsTimestampStart;
    num earningsTimestampEnd;
    num trailingAnnualDividendRate;
    num trailingPE;
    num trailingAnnualDividendYield;
    num epsTrailingTwelveMonths;
    num epsForward;
    num epsCurrentYear;
    num priceEpsCurrentYear;
    num sharesOutstanding;
    num bookValue;
    num fiftyDayAverage;
    num fiftyDayAverageChange;
    num fiftyDayAverageChangePercent;
    num twoHundredDayAverage;
    num twoHundredDayAverageChange;
    num twoHundredDayAverageChangePercent;
    num marketCap;
    num forwardPE;
    num priceToBook;
    num sourceInterval;
    num exchangeDataDelayedBy;
    String marketState;
    num gmtOffSetMilliseconds;
    bool esgPopulated;
    String exchange;
    String shortName;
    String longName;
    String messageBoardId;
    String exchangeTimezoneName;
    String market;
    bool tradeable;
    String exchangeTimezoneShortName;
    num firstTradeDateMilliseconds;
    num priceHint;
    String displayName;
    String symbol;

     

    YahooQuote(){language;
      this.region;
      this.quoteType;
      this.quoteSourceName;
      this.triggerable;
      this.currency;
      this.regularMarketChange;
      this.regularMarketChangePercent;
      this.regularMarketTime;
      this.regularMarketPrice;
      this.regularMarketDayHigh;
      this.regularMarketDayRange;
      this.regularMarketDayLow;
      this.regularMarketVolume;
      this.regularMarketPreviousClose;
      this.bid;
      this.ask;
      this.bidSize;
      this.askSize;
      this.fullExchangeName;
      this.financialCurrency;
      this.regularMarketOpen;
      this.averageDailyVolume3Month;
      this.averageDailyVolume10Day;
      this.fiftyTwoWeekLowChange;
      this.fiftyTwoWeekLowChangePercent;
      this.fiftyTwoWeekRange;
      this.fiftyTwoWeekHighChange;
      this.fiftyTwoWeekHighChangePercent;
      this.fiftyTwoWeekLow;
      this.fiftyTwoWeekHigh;
      this.dividendDate;
      this.earningsTimestamp;
      this.earningsTimestampStart;
      this.earningsTimestampEnd;
      this.trailingAnnualDividendRate;
      this.trailingPE;
      this.trailingAnnualDividendYield;
      this.epsTrailingTwelveMonths;
      this.epsForward;
      this.epsCurrentYear;
      this.priceEpsCurrentYear;
      this.sharesOutstanding;
      this.bookValue;
      this.fiftyDayAverage;
      this.fiftyDayAverageChange;
      this.fiftyDayAverageChangePercent;
      this.twoHundredDayAverage;
      this.twoHundredDayAverageChange;
      this.twoHundredDayAverageChangePercent;
      this.marketCap;
      forwardPE;
      priceToBook;
      sourceInterval;
      exchangeDataDelayedBy;
      marketState;
      gmtOffSetMilliseconds;
      esgPopulated;
      exchange;
      shortName;
      longName;
      messageBoardId;
      exchangeTimezoneName;
      market;
      tradeable;
      exchangeTimezoneShortName;
      firstTradeDateMilliseconds;
      priceHint;
      displayName;
      symbol;
    }
}