class YahooQuote{

  
    String language;
    String region;
    String quoteType;
    String quoteSourceName;
    bool triggerable;
    String currency;
    num regularMarketChange;
    num regularMarketChangePercent;
    num regularMarketTime;
    num regularMarketPrice;
    num regularMarketDayHigh;
    String regularMarketDayRange;
    num regularMarketDayLow;
    num regularMarketVolume;
    num regularMarketPreviousClose;
    num bid;
    num ask;
    num bidSize;
    num askSize;
    String fullExchangeName;
    String financialCurrency;
    num regularMarketOpen;
    num averageDailyVolume3Month;
    num averageDailyVolume10Day;
    num fiftyTwoWeekLowChange;
    num fiftyTwoWeekLowChangePercent;
    String fiftyTwoWeekRange;
    num fiftyTwoWeekHighChange;
    num fiftyTwoWeekHighChangePercent;
    num fiftyTwoWeekLow;
    num fiftyTwoWeekHigh;
    num dividendDate;
    num earningsTimestamp;
    num earningsTimestampStart;
    num earningsTimestampEnd;
    num trailingAnnualDividendRate;
    num trailingPE;
    num trailingAnnualDividendYield;
    num epsTrailingTwelveMonths;
    num epsForward;
    num epsCurrentYear;
    num priceEpsCurrentYear;
    num sharesOutstanding;
    num bookValue;
    num fiftyDayAverage;
    num fiftyDayAverageChange;
    num fiftyDayAverageChangePercent;
    num twoHundredDayAverage;
    num twoHundredDayAverageChange;
    num twoHundredDayAverageChangePercent;
    num marketCap;
    num forwardPE;
    num priceToBook;
    num sourceInterval;
    num exchangeDataDelayedBy;
    String marketState;
    num gmtOffSetMilliseconds;
    bool esgPopulated;
    String exchange;
    String shortName;
    String longName;
    String messageBoardId;
    String exchangeTimezoneName;
    String market;
    bool tradeable;
    String exchangeTimezoneShortName;
    num firstTradeDateMilliseconds;
    num priceHint;
    String displayName;
    String symbol;

     

    YahooQuote(){
      language;
     region;
     quoteType;
     quoteSourceName;
     triggerable;
     currency;
     regularMarketChange;
     regularMarketChangePercent;
     regularMarketTime;
     regularMarketPrice;
     regularMarketDayHigh;
     regularMarketDayRange;
     regularMarketDayLow;
     regularMarketVolume;
     regularMarketPreviousClose;
     bid;
     ask;
     bidSize;
     askSize;
     fullExchangeName;
     financialCurrency;
     regularMarketOpen;
     averageDailyVolume3Month;
     averageDailyVolume10Day;
     fiftyTwoWeekLowChange;
     fiftyTwoWeekLowChangePercent;
     fiftyTwoWeekRange;
     fiftyTwoWeekHighChange;
     fiftyTwoWeekHighChangePercent;
     fiftyTwoWeekLow;
     fiftyTwoWeekHigh;
     dividendDate;
     earningsTimestamp;
     earningsTimestampStart;
     earningsTimestampEnd;
     trailingAnnualDividendRate;
     trailingPE;
     trailingAnnualDividendYield;
     epsTrailingTwelveMonths;
     epsForward;
     epsCurrentYear;
     priceEpsCurrentYear;
     sharesOutstanding;
     bookValue;
     fiftyDayAverage;
     fiftyDayAverageChange;
     fiftyDayAverageChangePercent;
     twoHundredDayAverage;
     twoHundredDayAverageChange;
     twoHundredDayAverageChangePercent;
     marketCap;
     forwardPE;
     priceToBook;
     sourceInterval;
     exchangeDataDelayedBy;
     marketState;
     gmtOffSetMilliseconds;
     esgPopulated;
     exchange;
     shortName;
     longName;
     messageBoardId;
     exchangeTimezoneName;
     market;
     tradeable;
     exchangeTimezoneShortName;
     firstTradeDateMilliseconds;
     priceHint;
     symbol;
     displayName;
    }
}