class YahooQuote{

  
    String language;
    String region;
    String quoteType;
    String quoteSourceName;
    bool triggerable;
    String currency;
    num regularMarketChange;
    num regularMarketChangePercent;
    num regularMarketTime;
    num regularMarketPrice;
    num regularMarketDayHigh;
    String regularMarketDayRange;
    num regularMarketDayLow;
    num regularMarketVolume;
    num regularMarketPreviousClose;
    num bid;
    num ask;
    num bidSize;
    num askSize;
    String fullExchangeName;
    String financialCurrency;
    num regularMarketOpen;
    num averageDailyVolume3Month;
    num averageDailyVolume10Day;
    num fiftyTwoWeekLowChange;
    num fiftyTwoWeekLowChangePercent;
    String fiftyTwoWeekRange;
    num fiftyTwoWeekHighChange;
    num fiftyTwoWeekHighChangePercent;
    num fiftyTwoWeekLow;
    num fiftyTwoWeekHigh;
    num dividendDate;
    num earningsTimestamp;
    num earningsTimestampStart;
    num earningsTimestampEnd;
    num trailingAnnualDividendRate;
    num trailingPE;
    num trailingAnnualDividendYield;
    num epsTrailingTwelveMonths;
    num epsForward;
    num epsCurrentYear;
    num priceEpsCurrentYear;
    num sharesOutstanding;
    num bookValue;
    num fiftyDayAverage;
    num fiftyDayAverageChange;
    num fiftyDayAverageChangePercent;
    num twoHundredDayAverage;
    num twoHundredDayAverageChange;
    num twoHundredDayAverageChangePercent;
    num marketCap;
    num forwardPE;
    num priceToBook;
    num sourceInterval;
    num exchangeDataDelayedBy;
    String marketState;
    num gmtOffSetMilliseconds;
    bool esgPopulated;
    String exchange;
    String shortName;
    String longName;
    String messageBoardId;
    String exchangeTimezoneName;
    String market;
    bool tradeable;
    String exchangeTimezoneShortName;
    num firstTradeDateMilliseconds;
    num priceHint;
    String displayName;
    String symbol;

     

    YahooQuote(){language;
     thiregion;
     thiquoteType;
     thiquoteSourceName;
     thitriggerable;
     thicurrency;
     thiregularMarketChange;
     thiregularMarketChangePercent;
     thiregularMarketTime;
     thiregularMarketPrice;
     thiregularMarketDayHigh;
     thiregularMarketDayRange;
     thiregularMarketDayLow;
     thiregularMarketVolume;
     thiregularMarketPreviousClose;
     thibid;
     thiask;
     thibidSize;
     thiaskSize;
     thifullExchangeName;
     thifinancialCurrency;
     thiregularMarketOpen;
     thiaverageDailyVolume3Month;
     thiaverageDailyVolume10Day;
     thififtyTwoWeekLowChange;
     thififtyTwoWeekLowChangePercent;
     thififtyTwoWeekRange;
     thififtyTwoWeekHighChange;
     thififtyTwoWeekHighChangePercent;
     thififtyTwoWeekLow;
     thififtyTwoWeekHigh;
     thidividendDate;
     thiearningsTimestamp;
     thiearningsTimestampStart;
     thiearningsTimestampEnd;
     thitrailingAnnualDividendRate;
     thitrailingPE;
     thitrailingAnnualDividendYield;
     thiepsTrailingTwelveMonths;
     thiepsForward;
     thiepsCurrentYear;
     thipriceEpsCurrentYear;
     thisharesOutstanding;
     thibookValue;
     thififtyDayAverage;
     thififtyDayAverageChange;
     thififtyDayAverageChangePercent;
     thitwoHundredDayAverage;
     thitwoHundredDayAverageChange;
     thitwoHundredDayAverageChangePercent;
     thimarketCap;
     forwardPE;
     priceToBook;
     sourceInterval;
     exchangeDataDelayedBy;
     marketState;
     gmtOffSetMilliseconds;
     esgPopulated;
     exchange;
     shortName;
     longName;
     messageBoardId;
     exchangeTimezoneName;
     market;
     tradeable;
     exchangeTimezoneShortName;
     firstTradeDateMilliseconds;
     priceHint;
     displayName;
     symbol;
    }
}